[package]
name = "kitty"
version = "0.1.0"
edition = "2021"
author = "Jonatan Lima <jotanlima@gmail>"

[dependencies]
dotenv = "0.15.0"
mockall = "0.10.2"

[[test]]
name = "integration"
path = "tests/lib.rs"
