[package]
name = "kitty"
version = "0.1.0"
edition = "2021"
author = "Jonatan Lima <jotanlima@gmail>"

[dependencies]
mockall = "0.11.1"
directories = "4.0.1"

[[test]]
name = "integration"
path = "tests/lib.rs"
